SET GLOBAL max_allowed_packet=524288000;
show GLOBAL variables like 'max_allowed_packet';


DROP DATABASE IF EXISTS CONTACT;
CREATE DATABASE CONTACT;
USE CONTACT;

SHOW TABLES;


SELECT * FROM CONTACT;
SELECT * FROM MOBILE;
SELECT * FROM ADDRESS;
SELECT * FROM CONTACT_EMAIL;
SELECT * FROM CONTACT_DATE;

SELECT * FROM ST_USER;
SELECT * FROM CONTACT;
SELECT * FROM MOBILE;
SELECT * FROM CONTACT_EMAIL;
SELECT * FROM CONTACT_DATE;
SELECT * FROM ST_COUNTRY_CODE;
SELECT * FROM ST_ADDRESS_TYPE;
SELECT * FROM ADDRESS;
SELECT * FROM ST_COUNTRY;
SELECT * FROM ST_STATE;
SELECT * FROM ST_DISTRICT;
SELECT * FROM ST_ZIP_CODE;

SELECT COUNT(*) FROM ST_USER;
SELECT COUNT(*) FROM CONTACT;
SELECT COUNT(*) FROM MOBILE;
SELECT COUNT(*) FROM CONTACT_EMAIL;
SELECT COUNT(*) FROM CONTACT_DATE;
SELECT COUNT(*) FROM ST_COUNTRY_CODE;
SELECT COUNT(*) FROM ST_ADDRESS_TYPE;
SELECT COUNT(*) FROM ADDRESS;
SELECT COUNT(*) FROM ST_COUNTRY;
SELECT COUNT(*) FROM ST_STATE;
SELECT COUNT(*) FROM ST_DISTRICT;
SELECT COUNT(*) FROM ST_ZIP_CODE;


DESC ST_USER;
DESC CONTACT;
DESC MOBILE;
DESC ST_COUNTRY_CODE;
DESC ST_ADDRESS_TYPE;
DESC ADDRESS;
DESC ST_COUNTRY;
DESC ST_STATE;
DESC ST_DISTRICT;
DESC ST_ZIP_CODE;

DELETE FROM ST_USER;
DELETE FROM CONTACT_EMAIL;
DELETE FROM CONTACT_DATE;
DELETE FROM MOBILE;
DELETE FROM ST_COUNTRY_CODE;
DELETE FROM ADDRESS;
DELETE FROM ST_ADDRESS_TYPE;
DELETE FROM ST_ZIP_CODE;
DELETE FROM ST_DISTRICT;
DELETE FROM ST_STATE;
DELETE FROM ST_COUNTRY;
DELETE FROM CONTACT;

DROP TABLE ST_USER;


DROP TABLE CONTACT_EMAIL;
DROP TABLE CONTACT_DATE;
DROP TABLE MOBILE;
DROP TABLE ADDRESS;
DROP TABLE CONTACT;

DROP TABLE ST_COUNTRY_CODE;
DROP TABLE ST_ADDRESS_TYPE;
DROP TABLE ST_ZIP_CODE;
DROP TABLE ST_DISTRICT;
DROP TABLE ST_STATE;
DROP TABLE ST_COUNTRY;

